
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 14 22:08:03 CEST 2023
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 33;
  public static final int JUSQUA = 29;
  public static final int CSTENTIERE = 31;
  public static final int OU = 19;
  public static final int DOUBLEEQUAL = 21;
  public static final int PLUS = 15;
  public static final int PAR_OUVR = 4;
  public static final int EQUAL = 14;
  public static final int ECRIRE = 10;
  public static final int ALORS = 25;
  public static final int FONCTIONS = 3;
  public static final int VIRGULE = 9;
  public static final int REPETER = 28;
  public static final int NON = 20;
  public static final int INF = 23;
  public static final int MOINS = 17;
  public static final int POINTVIRGULE = 8;
  public static final int SINON = 26;
  public static final int VARIABLES = 2;
  public static final int FINREPETER = 30;
  public static final int ENTIER = 12;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int RETOURNER = 11;
  public static final int SI = 24;
  public static final int ET = 18;
  public static final int PAR_FERM = 5;
  public static final int error = 1;
  public static final int BOOL = 13;
  public static final int DIFF = 22;
  public static final int CSTBOOL = 32;
  public static final int DEBUT = 6;
  public static final int FINSI = 27;
  public static final int FIN = 7;
}

